n1=float(input("Informe a primeira nota bimestral:"))
n2=float(input("Informe a segunda nota bimestral:"))
n3=float(input("Informe a terceira nota bimestral:"))
n4=float(input("Informe a quarta nota bimestral:"))
s=(n1+n2+n3+n4)
media=(s/4)
print("A media é de %d " % media)
